[tool.poetry]
name = "backend"
version = "0.1.1"
description = ""
authors = ["Ward Meersman <wardmeersman@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
fastapi = "^0.84.0"
uvicorn = "^0.18.3"
alembic = "^1.8.1"
coverage = "^6.4.4"
SQLAlchemy = "^1.4.41"
pyhumps = "^3.7.3"


[tool.poetry.group.dev.dependencies]
pytest = "^7.1.3"
mypy = "^0.971"
pylint = "^2.15.0"
sqlalchemy2-stubs = "^0.0.2a27"

[tool.mypy]
plugins = ["sqlalchemy.ext.mypy.plugin"]

[[tool.mypy.overrides]]
module = "sqlalchemy_utils"
ignore_errors = true

[[tool.mypy.overrides]]
module = "pyhumps"
ignore_errors = true

[tool.pylint.master]
extension-pkg-whitelist = "pydantic"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"