[tool.poetry]
name = "backend"
version = "0.1.1"
description = ""
authors = ["Ward Meersman <wardmeersman@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
fastapi = "^0.82.0"
uvicorn = "^0.18.3"
alembic = "^1.8.1"
coverage = "^6.4.4"
SQLAlchemy = "^1.4.41"


[tool.poetry.group.dev.dependencies]
pytest = "^7.1.3"
mypy = "^0.971"
pylint = "^2.15.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
