"""init database

Revision ID: 3d4f0e46fb70
Revises: a219f2ee97cb
Create Date: 2022-09-26 21:18:43.832668

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d4f0e46fb70'
down_revision = 'a219f2ee97cb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('card_games', schema=None) as batch_op:
        batch_op.add_column(sa.Column('guessed', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('card_games', schema=None) as batch_op:
        batch_op.drop_column('guessed')

    # ### end Alembic commands ###
