"""create database

Revision ID: 9d088dc429e6
Revises: 
Create Date: 2022-09-13 17:05:50.453175

"""
# pylint: disable-all
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d088dc429e6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('games',
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('round_one_done', sa.Boolean(), nullable=False),
    sa.Column('round_two_done', sa.Boolean(), nullable=False),
    sa.Column('round_three_done', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('game_id')
    )
    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_games_game_id'), ['game_id'], unique=False)

    op.create_table('teams',
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=True),
    sa.Column('team_name', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.game_id'], ),
    sa.PrimaryKeyConstraint('team_id')
    )
    with op.batch_alter_table('teams', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_teams_team_id'), ['team_id'], unique=False)

    op.create_table('players',
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['teams.team_id'], ),
    sa.PrimaryKeyConstraint('player_id')
    )
    with op.batch_alter_table('players', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_players_player_id'), ['player_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('players', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_players_player_id'))

    op.drop_table('players')
    with op.batch_alter_table('teams', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_teams_team_id'))

    op.drop_table('teams')
    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_games_game_id'))

    op.drop_table('games')
    # ### end Alembic commands ###
