"""init database

Revision ID: d6647097f6cb
Revises: 3d4f0e46fb70
Create Date: 2022-09-27 14:13:05.021827

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd6647097f6cb'
down_revision = '3d4f0e46fb70'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.add_column(sa.Column('next_team_index', sa.Integer(), nullable=True))

    with op.batch_alter_table('teams', schema=None) as batch_op:
        batch_op.add_column(sa.Column('next_player_index', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teams', schema=None) as batch_op:
        batch_op.drop_column('next_player_index')

    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.drop_column('next_team_index')

    # ### end Alembic commands ###
