"""Setup database

Revision ID: e171f09bbcba
Revises: cf7cf3ea013c
Create Date: 2022-09-25 15:04:06.621858

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e171f09bbcba'
down_revision = 'cf7cf3ea013c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
